version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  mqtt-broker:
    build: .
    container_name: mqtt-broker
    restart: always
    env_file: .env
    depends_on:
      - redis
    ports:
      - "8883:8883"  # TLS
      - "1883:1883"  # TCP
      - "3001:3001"  # HTTP metrics
    volumes:
      - ./broker.crt:/app/broker.crt:ro
      - ./broker.key:/app/broker.key:ro
